# Generated by Django 3.2.6 on 2022-05-07 12:55

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='poster',
            field=models.ImageField(default=datetime.datetime(2022, 5, 7, 12, 55, 54, 751466, tzinfo=utc), upload_to='movie_posters/'),
            preserve_default=False,
        ),
    ]
