# Generated by Django 3.2.6 on 2022-05-10 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0003_auto_20220510_1725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='duration',
            field=models.CharField(blank=True, max_length=50, verbose_name='Duration'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='quality',
            field=models.CharField(blank=True, max_length=50, verbose_name='Quality'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='short_description',
            field=models.CharField(blank=True, max_length=550, verbose_name='Short title'),
        ),
    ]
