# Generated by Django 3.2.6 on 2022-04-14 12:57

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='actors',
            name='image',
            field=models.ImageField(default=datetime.datetime(2022, 4, 14, 12, 57, 12, 341725, tzinfo=utc), upload_to='actor_images/'),
            preserve_default=False,
        ),
    ]
