# Generated by Django 3.2.6 on 2022-04-16 13:34

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20220414_1839'),
    ]

    operations = [
        migrations.AddField(
            model_name='actors',
            name='info',
            field=models.TextField(default=datetime.datetime(2022, 4, 16, 13, 34, 56, 687786, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='movie',
            name='actors',
            field=models.ManyToManyField(related_name='movies', to='main.Actors'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movies', to='main.category'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='genre',
            field=models.ManyToManyField(related_name='movies', to='main.Genre'),
        ),
    ]
