# Generated by Django 3.2.4 on 2021-06-05 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_post_views'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Ismingiz')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('subject', models.CharField(max_length=150, verbose_name='Mavzu')),
                ('comment', models.TextField(verbose_name='Xabar matni')),
            ],
            options={
                'verbose_name': 'Muhokama',
                'verbose_name_plural': 'Muhokamalar',
            },
        ),
    ]
