# Generated by Django 3.2.4 on 2021-06-08 12:32

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_comment_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2021, 6, 8, 12, 32, 43, 516045, tzinfo=utc), verbose_name='Bildirilgan sana'),
            preserve_default=False,
        ),
    ]
