# Generated by Django 3.2.6 on 2021-11-18 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AllFields',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strings', models.CharField(blank=True, max_length=20, verbose_name='Chars')),
                ('texts', models.TextField(verbose_name='Text')),
                ('email', models.EmailField(blank=True, max_length=100, verbose_name='Email')),
                ('url', models.URLField(blank=True, max_length=100, verbose_name='URL')),
                ('slug', models.SlugField(unique=True, verbose_name='*')),
                ('yesorno', models.BooleanField(default=True, verbose_name='on/off')),
                ('number', models.IntegerField(verbose_name='Integer')),
                ('floatNumber', models.FloatField(verbose_name='Float')),
                ('decimalNumber', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Decimal')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Date')),
                ('dateAndTime', models.DateTimeField(auto_now=True, verbose_name='Date and Time')),
            ],
        ),
    ]
