# Generated by Django 3.2.6 on 2021-11-09 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('age', models.PositiveIntegerField(default=0)),
                ('adress', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=20)),
            ],
        ),
    ]
